# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Terminal 1
    before: echo 'Before script'
    init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: Terminal 2
    init: npm install'
    command: npm rum dev
  - name: Terminal 3
    init: echo 'Este é o Terminal 3'
    command: echo 'Terminal 3'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
